### ISSUE TITLE
Issue with Components Directory?

### ISSUE THREAD

**Issue by ryansolid** [theSherwood/7_GUIs#5]
If you don't mind me asking what was it exactly? I really lamented over adding hot reloading but the problem is the method I use(as discussed in that issue) needs to only apply to components so I used the directory mechanism with template. If it's broken or you hit issues it would be great to know. I realize I under documented that change and plan to rectify it, but I'd be interested to hear your experience.

**Comment by theSherwood** [comment]
Sure thing! I figured it had to be something to do with the hot reloading. Something of note is that there were no issues when running `npm run start` or `solid-scripts start`. But on `npm run build` I was getting this:

```
Creating an optimized production build...
Failed to compile.

./src/tasks/Cells/Cells.js
Attempted import error: '../../components/Card' does not contain a default export (imported as 'Card').


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! solid-guis@0.1.0 build: `solid-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the solid-guis@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It simply wasn't finding the default export.

**Comment by ryansolid** [comment]
Whew ok already fixed that one I think: https://github.com/ryansolid/solid/issues/118.

**Comment by theSherwood** [comment]
Not at all. I appreciate that you want Solid to be the best it can be. It makes more more confident using it.
